mybatis:
  mapper-locations: mybatis/*.xml
  configuration:
    default-statement-timeout: 5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: javaee
server:
  port: 8090